version: '3'

services: 
  neo4j:
    image: neo4j
    restart: always
    ports: 
      - 7474:7474
      - 7687:7687
    volumes: 
      - ./tmp:/data
    environment:
      - NEO4J_AUTH=neo4j/password
